name: Build
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      CCACHE_COMPRESS: 'true'
      CCACHE_COMPRESSLEVEL: '6'
      CCACHE_MAXSIZE: '500M'
      CCACHE_WIN_VERSION: 3.7.7
      MACOSX_DEPLOYMENT_TARGET: 10.12
    strategy:
      matrix:
        config:
          - name: "Windows Latest MSVC"
            os: windows-latest
            triplet: x64-windows
            cmake_config: >-
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
              -DCMAKE_BUILD_TYPE=Release
              -GNinja
          - name: "macOS Latest Clang"
            os: macos-latest
            triplet: x64-osx
            cmake_config: >-
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
              -DCMAKE_BUILD_TYPE=Release
              -GNinja
          - name: "Ubuntu Latest GCC"
            os: ubuntu-latest
            triplet: x64-linux
            cmake_config: >-
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
              -DCMAKE_BUILD_TYPE=Release
              -GNinja
    steps:
      # checkout to workspace
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get CMake and ninja
        uses: lukka/get-cmake@v3.20.1

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgArguments: 'boost-variant boost-optional boost-format boost-functional boost-range boost-iterator'
          vcpkgTriplet: '${{ matrix.config.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'

      - name: 'Install ubuntu dependencies'
        if: matrix.config.os == 'ubuntu-latest'
        run: sudo apt-get install -y ccache

      - name: 'Install ccache on windows'
        if: matrix.config.os == 'windows-latest'
        shell: cmake -P {0}
        run: |
          set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_WIN_VERSION}/Windows.tar.xz")
          file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
        working-directory: ${{ runner.workspace }}

      - name: 'Install ccache on macos'
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install ccache

      - name: 'Config env for ccache'
        run: |
          echo "${{ runner.workspace }}" >> $GITHUB_PATH
          echo "CCACHE_BASEDIR=${{ github.workspace }}" >> $GITHUB_ENV
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
        shell: bash

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ runner.workspace }}/.ccache
          key: ${{ matrix.config.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
              ${{ matrix.config.name }}-ccache-

      - name: 'zero ccache stats'
        run: ccache -z

      - name: 'print ccache config'
        run: ccache -p

      - name: 'Build with CMake and Ninja'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/b/ninja'
          cmakeAppendedArgs: '${{ matrix.config.cmake_config }}'

      - name: 'print ccache stats'
        run: ccache -s

      - name: 'Run tests'
        run: ctest . --output-on-failure
        working-directory: '${{ runner.workspace }}/b/ninja'
